kind: pipeline
name: default
steps:

  - name: app-build
    image: php:7.4-fpm
    context: .
    dockerfile: Dockerfile
    settings:
      tags: app-dev
      debug: true
      volumes:
        - name: app
          path: ./app:/var/www/html
        - name: vendor
          path: /var/www/html/vendor
        - name: node_modules
          path: /var/www/html/node_modules
      ports:
        - '9000:9000'
      networks:
        - app

  - name: Run
    image: alpine
    commands:
      - 'docker-compose up --build -d'
    
