version: "3"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    depends_on: 
      - app
      - db
    networks:
      - app
    ports:
      - '8081:81'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app
    environment:
      MYSQL_DADATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - '9000:9000'
    networks:
      - app
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8000:8080
    networks:
      - app
    
networks:
  app:
    
    
